// swift-tools-version: 5.10
import PackageDescription

// Layout aligned with commit b018a4a:
//   CForgeCore (systemLibrary) → ForgeCore (Swift wrapper) → DarwinForgeUI → DarwinForgeApp
//   + ForgeCoreTests
// libforge_core.a is produced by `make app` (Rust) and copied into
// Vendor/CForgeCore/lib/. Header forge_core.h is generated by cbindgen.

let package = Package(
    name: "DarwinForge",
    platforms: [
        .macOS(.v14)
    ],
    products: [
        .executable(name: "DarwinForgeApp", targets: ["DarwinForgeApp"]),
        .library(name: "ForgeCore", targets: ["ForgeCore"]),
        .library(name: "DarwinForgeUI", targets: ["DarwinForgeUI"])
    ],
    targets: [
        .systemLibrary(
            name: "CForgeCore",
            path: "Vendor/CForgeCore/include"
        ),
        .target(
            name: "ForgeCore",
            dependencies: ["CForgeCore"],
            path: "Sources/ForgeCore",
            linkerSettings: [
                .unsafeFlags(["-LVendor/CForgeCore/lib"])
            ]
        ),
        .target(
            name: "DarwinForgeUI",
            dependencies: ["ForgeCore"],
            path: "Sources/DarwinForgeUI",
            resources: [
                .copy("Resources/Meshes")
            ]
        ),
        .executableTarget(
            name: "DarwinForgeApp",
            dependencies: ["DarwinForgeUI"],
            path: "Sources/DarwinForgeApp"
        ),
        .testTarget(
            name: "ForgeCoreTests",
            dependencies: ["ForgeCore"],
            path: "Tests/ForgeCoreTests"
        ),
        .testTarget(
            name: "DarwinForgeUITests",
            dependencies: ["DarwinForgeUI"],
            path: "Tests/DarwinForgeUITests"
        )
    ]
)
