// swift-tools-version: 5.10
import PackageDescription

// Layout aligned with commit b018a4a:
//   CForgeCore (systemLibrary) → ForgeCore (Swift wrapper) → DarwinForgeUI → DarwinForgeApp
//   + ForgeCoreTests
// libforge_core.a is produced by `make app` (Rust) and copied into
// Vendor/CForgeCore/lib/. Header forge_core.h is generated by cbindgen.

let package = Package(
    name: "DarwinForge",
    // 2026-05-16: default localization — 한국어 사용자 우선.
    // 다른 locale 미지원 시 ko 사용. Base.lproj = English fallback.
    defaultLocalization: "ko",
    platforms: [
        .macOS(.v14)
    ],
    products: [
        .executable(name: "DarwinForgeApp", targets: ["DarwinForgeApp"]),
        .library(name: "ForgeCore", targets: ["ForgeCore"]),
        .library(name: "DarwinForgeUI", targets: ["DarwinForgeUI"])
    ],
    targets: [
        .systemLibrary(
            name: "CForgeCore",
            path: "Vendor/CForgeCore/include"
        ),
        .target(
            name: "ForgeCore",
            dependencies: ["CForgeCore"],
            path: "Sources/ForgeCore",
            linkerSettings: [
                .unsafeFlags(["-LVendor/CForgeCore/lib"])
            ]
        ),
        .target(
            name: "DarwinForgeUI",
            dependencies: ["ForgeCore"],
            path: "Sources/DarwinForgeUI",
            resources: [
                .copy("Resources/Meshes"),
                // 2026-05-16: Localization 스캐폴드 — ko / Base.
                // 향후 영어/일본어 등 추가 가능.
                .process("Resources/ko.lproj"),
                .process("Resources/Base.lproj"),
            ]
        ),
        .executableTarget(
            name: "DarwinForgeApp",
            dependencies: ["DarwinForgeUI"],
            path: "Sources/DarwinForgeApp",
            resources: [
                // 2026-05-16: PNG 앱 아이콘 — 코드 생성 OP 도형 대체.
                // Dock / Cmd-Tab / Finder 미리보기 모두 이 PNG 사용.
                .copy("Resources/AppIcon.png")
            ]
        ),
        .testTarget(
            name: "ForgeCoreTests",
            dependencies: ["ForgeCore"],
            path: "Tests/ForgeCoreTests"
        ),
        .testTarget(
            name: "DarwinForgeUITests",
            dependencies: ["DarwinForgeUI"],
            path: "Tests/DarwinForgeUITests"
        )
    ]
)
