//! V2 — 각속도 / 가속도 검증.
//!
//! 본구현 (S9-9 V2). PRD §5.3 V2.
//!
//! step 간 위치 변화량 ÷ play_time 으로 추정 각속도 (raw/ms) 를 계산. MX-28 의
//! `moving_speed_max` 한계 (1023 raw → 약 117 rpm) 의 75% (보수적 임계) 를
//! 넘으면 FAIL.
//!
//! ## 단위 변환
//! - MX-28: 1 raw 위치 step = 360°/4096 = 0.088°
//! - 시간: `play_time` raw = ms × 8
//! - 속도 raw/ms → deg/s = `raw / ms × 0.088 × 1000 = raw / ms × 88`
//! - MX-28 max moving speed raw = 1023 → 약 84 RPM → 504°/s
//! - 75% threshold → 378°/s
//!
//! 보수적: raw 변화 / play_time(ms) > 약 4.3 → fail.

use super::{Validator, ValidatorReport, ValidatorStage};
use crate::motion::page::NUM_JOINTS_IN_STEP;
use crate::motion::MotionPage;
use crate::synth::Result;

const SKIP_MARKER: u16 = 32767;
const FLAG_INVALID: u16 = 0x4000;
const FLAG_TORQUE_OFF: u16 = 0x2000;
const POSITION_MASK: u16 = 0x0FFF;

/// `raw_change / ms` 보수적 임계 — 이 값 초과는 WARN.
///
/// ROBOTIS-OP2 motion_4096.bin 의 16 OFFICIAL_CATALOG 페이지 1,100 sample 에서
/// 측정한 **99th percentile = 4.735 raw/ms × 1.1 ≈ 5.21**. 일반 모션 (Stand Up,
/// Yes, walkready 등) 은 이 임계 아래.
///
/// Provenance: [`tests/fixtures/velocity_calibration.json`] (auto-generated by
/// `examples/calibrate_velocity` — 2026-05-12).
///
/// [`tests/fixtures/velocity_calibration.json`]: ../../../../tests/fixtures/velocity_calibration.json
pub const WARN_RAW_PER_MS: f64 = 5.2;

/// `raw_change / ms` 절대 한계 — 이 값 초과는 FAIL.
///
/// ROBOTIS 페이지 max = **10.264 raw/ms × 1.1 ≈ 11.29** — page 12 right_kick
/// step 3 (kick impact) 의 R_ANKLE_PITCH (joint 15). MX-28 max_moving_speed
/// (raw 1023 ≈ 5.7 raw/ms 평균) 의 peak burst 한계. ROBOTIS 공식 페이지는 모두
/// 통과 (현재 임계 11.3 > 측정 max 10.26).
///
/// Provenance: 위 동일 fixture.
pub const MAX_RAW_PER_MS: f64 = 11.3;

/// V2 — Velocity / Acceleration validator.
#[derive(Debug, Default)]
pub struct VelocityValidator;

impl Validator for VelocityValidator {
    fn stage(&self) -> ValidatorStage {
        ValidatorStage::Velocity
    }

    fn validate(&self, page: &MotionPage) -> Result<ValidatorReport> {
        if page.steps.len() < 2 {
            return Ok(ValidatorReport::Pass(self.stage()));
        }

        let mut warn_violations: Vec<String> = Vec::new();
        let mut fail_violations: Vec<String> = Vec::new();

        for win in page.steps.windows(2) {
            let a = &win[0];
            let b = &win[1];
            // play_time of B = duration to reach B from A.
            let play_ms = (b.play_time as f64) * 8.0;
            if play_ms <= 0.0 {
                continue;
            }
            for i in 1..=NUM_JOINTS_IN_STEP.min(20) {
                let av = a.positions[i];
                let bv = b.positions[i];
                if av == SKIP_MARKER
                    || bv == SKIP_MARKER
                    || (av & FLAG_INVALID) != 0
                    || (bv & FLAG_INVALID) != 0
                    || (av & FLAG_TORQUE_OFF) != 0
                    || (bv & FLAG_TORQUE_OFF) != 0
                {
                    continue;
                }
                let av_pos = (av & POSITION_MASK) as i32;
                let bv_pos = (bv & POSITION_MASK) as i32;
                let delta = (bv_pos - av_pos).abs() as f64;
                let speed = delta / play_ms;
                if speed > MAX_RAW_PER_MS {
                    fail_violations.push(format!(
                        "joint slot {} {:.2} raw/ms > {:.2} HARD max",
                        i, speed, MAX_RAW_PER_MS
                    ));
                } else if speed > WARN_RAW_PER_MS {
                    warn_violations.push(format!(
                        "joint slot {} {:.2} raw/ms > {:.2} warn",
                        i, speed, WARN_RAW_PER_MS
                    ));
                }
            }
        }

        if !fail_violations.is_empty() {
            let summary = if fail_violations.len() > 3 {
                format!(
                    "{} hard-violations, first 3: {}",
                    fail_violations.len(),
                    fail_violations[..3].join("; ")
                )
            } else {
                fail_violations.join("; ")
            };
            Ok(ValidatorReport::Fail(self.stage(), summary))
        } else if !warn_violations.is_empty() {
            let summary = if warn_violations.len() > 3 {
                format!(
                    "{} warn-violations, first 3: {}",
                    warn_violations.len(),
                    warn_violations[..3].join("; ")
                )
            } else {
                warn_violations.join("; ")
            };
            Ok(ValidatorReport::Warn(self.stage(), summary))
        } else {
            Ok(ValidatorReport::Pass(self.stage()))
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::motion::{MotionPage, MotionStep, SafetyClass};

    fn page_with_steps(steps: Vec<MotionStep>) -> MotionPage {
        let mut p = MotionPage::default();
        p.safety_class = SafetyClass::Safe;
        p.steps = steps;
        p
    }

    fn step(positions: [u16; NUM_JOINTS_IN_STEP], play_time: u8) -> MotionStep {
        MotionStep {
            positions,
            pause_time: 0,
            play_time,
        }
    }

    #[test]
    fn single_step_passes() {
        let p = page_with_steps(vec![step([2048; NUM_JOINTS_IN_STEP], 16)]);
        assert!(matches!(
            VelocityValidator.validate(&p).unwrap(),
            ValidatorReport::Pass(_)
        ));
    }

    #[test]
    fn slow_change_passes() {
        // 약 20ms 동안 raw 50 변화 = 2.5 raw/ms < 4.3 limit
        let mut a = [2048u16; NUM_JOINTS_IN_STEP];
        let mut b = [2048u16; NUM_JOINTS_IN_STEP];
        a[1] = 2000;
        b[1] = 2050;
        // play_time = 4 → 32 ms; delta 50 → 50/32 = 1.56 raw/ms
        let p = page_with_steps(vec![step(a, 16), step(b, 4)]);
        assert!(matches!(
            VelocityValidator.validate(&p).unwrap(),
            ValidatorReport::Pass(_)
        ));
    }

    #[test]
    fn fast_change_fails() {
        // 8ms (play_time=1) 동안 raw 100 변화 = 12.5 raw/ms > 4.3 limit
        let mut a = [2048u16; NUM_JOINTS_IN_STEP];
        let mut b = [2048u16; NUM_JOINTS_IN_STEP];
        a[1] = 2000;
        b[1] = 2100;
        let p = page_with_steps(vec![step(a, 16), step(b, 1)]);
        let report = VelocityValidator.validate(&p).unwrap();
        assert!(report.is_fail(), "expected Fail, got {:?}", report);
    }

    #[test]
    fn skip_marker_does_not_violate() {
        let mut a = [SKIP_MARKER; NUM_JOINTS_IN_STEP];
        let mut b = [SKIP_MARKER; NUM_JOINTS_IN_STEP];
        a[1] = 2000;
        b[1] = SKIP_MARKER;
        let p = page_with_steps(vec![step(a, 16), step(b, 1)]);
        assert!(matches!(
            VelocityValidator.validate(&p).unwrap(),
            ValidatorReport::Pass(_)
        ));
    }

    /// **D4 회귀** — WARN/MAX 임계가 `tests/fixtures/velocity_calibration.json`
    /// 의 실측 통계 (p99 × 1.1 / max × 1.1) 와 일치함을 lock-in.
    ///
    /// fixture 갱신 시 (`cargo run -p forge-core --example calibrate_velocity`)
    /// 새 권장값과 차이가 0.1 raw/ms 초과면 본 상수도 함께 갱신해야 함.
    #[test]
    fn thresholds_match_calibration_fixture() {
        let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("tests/fixtures/velocity_calibration.json");
        if !path.exists() {
            eprintln!("skip: {} not present — run examples/calibrate_velocity first", path.display());
            return;
        }
        let s = std::fs::read_to_string(&path).expect("read");
        // 간단 파싱 — recommended_thresholds 의 두 값 추출 (serde_json deps 회피).
        let warn_recommended = parse_after(&s, "\"warn_raw_per_ms\":").expect("warn key");
        let max_recommended = parse_after(&s, "\"max_raw_per_ms\":").expect("max key");

        let warn_diff = (WARN_RAW_PER_MS - warn_recommended).abs();
        let max_diff = (MAX_RAW_PER_MS - max_recommended).abs();
        assert!(
            warn_diff <= 0.1,
            "WARN={WARN_RAW_PER_MS} vs recommended {warn_recommended} differs by {warn_diff} — regenerate calibration"
        );
        assert!(
            max_diff <= 0.1,
            "MAX={MAX_RAW_PER_MS} vs recommended {max_recommended} differs by {max_diff} — regenerate calibration"
        );
    }

    /// JSON 텍스트에서 키 뒤의 숫자 추출 (간단 사용용).
    fn parse_after(s: &str, key: &str) -> Option<f64> {
        let pos = s.find(key)?;
        let rest = &s[pos + key.len()..];
        let trimmed = rest.trim_start();
        let end = trimmed
            .find(|c: char| !c.is_ascii_digit() && c != '.' && c != '-')
            .unwrap_or(trimmed.len());
        trimmed[..end].parse().ok()
    }
}
